import '@/node_modules/react-modal-video/css/modal-video.css';
import './globals.css';
import '../public/assets/css/style.css';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/free-mode';

import { DM_Sans, Marcellus } from '@/lib/font';

export const metadata = {
  title: 'Nexpeak | Legal Strength of Business',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico', 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${DM_Sans.variable} ${Marcellus.variable}`}>
       <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
       
      </head>
      <body>{children}</body>
    </html>
  );
}
